name: Run tests
on:
  pull_request:
    branches:
      - dev-temp
    types:
      - opened
      - synchronize
      - edited

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v3
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Free space
        run: df -h
      - name: Run tests
        run: docker build -f Dockerfile.tests -t creatorchainnetwork/node:test .
      - name: Free space
        run: df -h
